name: Frontend CI

on:
  push:
    branches:
      - staging-frontend
  workflow_dispatch:

env:
  IMAGE_REPO: 629490206392.dkr.ecr.eu-central-1.amazonaws.com/demo/frontend
  IMAGE_TAG: ${{ github.run_number }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      tag: ${{ env.IMAGE_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEYS }}
          aws-secret-access-key: ${{ secrets.SECRET_KEYS }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker image to ECR
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}

  update-gitops:
    needs: [build-and-push]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone GitOps repo (staging branch)
        uses: actions/checkout@v4
        with:
          repository: zubairzb/demo-gitops
          ref: staging
          token: ${{ secrets.PAT }}
          path: gitops

      - name: Update values.yaml and image-version.txt
        run: |
          cd gitops
          TAG=${{ github.run_number }}
          echo "Using tag: $TAG"

          # Update values.yaml
          sed -i "s/tag: .*/tag: $TAG/" ./frontend/values.yaml

          # Save to image-version.txt
          echo "$TAG" > ./frontend/image-version.txt

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add ./frontend/values.yaml image-version.txt
            git commit -m "Update frontend image tag to $TAG"
            git push origin staging
          fi

