name: Terraform Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEYS }}
          aws-secret-access-key: ${{ secrets.SECRET_KEYS }}
          aws-region: eu-central-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7 # Change to your preferred version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan -var-file="env.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
